// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBokMJpvS-lHRI5P9JJG5QJ0KWTbPIxIFc',
    appId: '1:1077286876589:web:59dc2ee23b774daaf7dd24',
    messagingSenderId: '1077286876589',
    projectId: 'mvccommers-66cdf',
    authDomain: 'mvccommers-66cdf.firebaseapp.com',
    storageBucket: 'mvccommers-66cdf.firebasestorage.app',
    measurementId: 'G-PK1SFCB0RZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWZjiP2CkzDcHCSV75_yKjTB7fLVD0egs',
    appId: '1:1077286876589:android:8d12654af2da7910f7dd24',
    messagingSenderId: '1077286876589',
    projectId: 'mvccommers-66cdf',
    storageBucket: 'mvccommers-66cdf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIA1rn0l4XAb1GvhyPbdDpocobEEAeZ3A',
    appId: '1:1077286876589:ios:365ed62781dd80d7f7dd24',
    messagingSenderId: '1077286876589',
    projectId: 'mvccommers-66cdf',
    storageBucket: 'mvccommers-66cdf.firebasestorage.app',
    iosBundleId: 'com.example.mvcCommers',
  );
}
